version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A app worker -l info -p eventlet
    depends_on:
      - redis
      - db
    env_file: .env

  celery-beat:
    build: .
    command: celery -A app beat -l info
    depends_on:
      - redis
      - db
    env_file: .env

volumes:
  postgres_data:
