# Generated by Django 5.1.5 on 2025-01-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="subs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="college.subscription",
            ),
        ),
    ]
